# -*- coding: utf-8 -*-
"""Questão6_professor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FeCKEVxn63ysCRNirsQlDOaVecDjD6H-
"""

#1. Quantos personagens existe nessa lista?

import pandas as pd

rick_morty_df = pd.read_json("https://raw.githubusercontent.com/jeffersonchaves/rick-and-morty-dados/main/character.json")

#display(rick_morty_df)

linha = rick_morty_df.shape

#print(f'existem {linha[0]} personagens nesse arquivo.')

#2. Quantos personagens são humanos?
#3. Quantos personagens são alienígenas?

rick_morty_df = pd.read_json("https://raw.githubusercontent.com/jeffersonchaves/rick-and-morty-dados/main/character.json")

alien_condicao = rick_morty_df['species'] == 'Alien'

alien_df = rick_morty_df.loc[alien_condicao]

numero_aliens, coluna = alien_df.shape

print(f'existem {numero_aliens} Aliens nesse arquivo.')

#4. Há quantos tipos de alienígenas diferentes?
x = alien_df['type'].value_counts()
numero_tipos_alienigena = x.shape

print(f'Há {numero_tipos_alienigena[0]} tipos de alienígenas diferentes')

#6. Qual o nome do episódio em que o personagem Crocubot aparece?
rick_morty_df = pd.read_json("https://raw.githubusercontent.com/jeffersonchaves/rick-and-morty-dados/main/character.json")
episodies_df = pd.read_json("https://raw.githubusercontent.com/jeffersonchaves/rick-and-morty-dados/main/episode.json")

crocubot_condicao = rick_morty_df['name'] == 'Crocubot'

crocubot = rick_morty_df.loc[crocubot_condicao]

episodio = crocubot['episode']
episodio = episodio[80][0]

episodio = episodio.split('/')

episodio = int(episodio[-1])

episodio

